# k8s/jobs/manual/selenium-test-chrome.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: selenium-test-chrome
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: selenium-test
          image: your-dockerhub-username/k8s-selenium:test
          env:
            - name: BROWSER
              value: "chrome"
            - name: HUB_URL
              value: "http://selenium-hub:4444/wd/hub"
            - name: APP_URL
              value: "http://web-app:8080"
      restartPolicy: Never