apiVersion: batch/v1
kind: Job
metadata:
  name: ${JOB_NAME}
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: selenium-test
          image: ${DOCKER_USERNAME}/k8s-selenium:test-${IMAGE_TAG}
          imagePullPolicy: Always
          env:
            - name: HUB_URL
              value: "http://selenium-hub:4444/wd/hub"
            - name: APP_URL
              value: "http://web-app:8080"
            - name: BROWSER
              value: "${BROWSER}"
      restartPolicy: Never