name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package -DskipTests
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: target/*.jar

  docker-build-and-push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: target

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Web App Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/k8s-selenium:web-app-${{ github.sha }}

      - name: Build and push Test Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.test
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/k8s-selenium:test-${{ github.sha }}

  deploy:
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
      - name: Update Kubernetes deployment
        run: |
          kubectl set image deployment/web-app web-app=${{ secrets.DOCKERHUB_USERNAME }}/k8s-selenium:web-app-${{ github.sha }}
          kubectl rollout status deployment/web-app

  test:
    needs: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [ chrome, firefox, edge ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
      - name: Run Selenium Test
        run: |
          job_name="selenium-test-job-${{ matrix.browser }}"
          kubectl delete job ${job_name} --ignore-not-found
          
          sed -e "s|\${JOB_NAME}|${job_name}|g" \
              -e "s|\${DOCKER_USERNAME}|${{ secrets.DOCKERHUB_USERNAME }}|g" \
              -e "s|\${IMAGE_TAG}|${{ github.sha }}|g" \
              -e "s|\${BROWSER}|${{ matrix.browser }}|g" \
              k8s/jobs/pipeline/selenium-test-job.yaml | \
          kubectl create -f -
          
          start_time=$(date +%s)
          timeout=300
          test_status="Unknown"
          
          while true; do
            status=$(kubectl get job ${job_name} -o jsonpath='{.status.conditions[?(@.type=="Complete")].status}')
            failed=$(kubectl get job ${job_name} -o jsonpath='{.status.conditions[?(@.type=="Failed")].status}')
          
            if [ "$status" == "True" ]; then
              test_status="Completed"
              break
            elif [ "$failed" == "True" ]; then
              test_status="Failed"
              break
            fi
          
            current_time=$(date +%s)
            elapsed=$((current_time - start_time))
          
            if [ $elapsed -ge $timeout ]; then
              test_status="Timed out"
              break
            fi
          
            sleep 5
          done
          
          # Collect logs regardless of the outcome
          kubectl logs job/${job_name} > ${{ matrix.browser }}-test-results.log || true
          
          echo "Test status: $test_status" >> ${{ matrix.browser }}-test-results.log
          
          if [ "$test_status" != "Completed" ]; then
            echo "${{ matrix.browser }} tests $test_status"
            exit 1
          else
            echo "${{ matrix.browser }} tests completed successfully"
          fi
      - name: Upload test logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.browser }}-logs
          path: ${{ matrix.browser }}-test-results.log